### ISSUE TITLE
Create Extension Icon Image

### ISSUE THREAD

**Issue by ExploreLearnMake** [rsc-media/extension-pack-webdev-student#2]
Need to create an image that will appear in the marketplace as the icon. It should be a PNG file. One idea is to include the Rio logo with HTML element brackets around it. 

- [x] Create icon for extension pack
- [x] Upload to GitHub
- [x] Once the file name and location are known, update the package.json file with the relative path.

**Comment by ExploreLearnMake** [comment]
Since the Rio logo cannot be used without getting permission first, next idea is to:
* Take the current CIS233DA course icon with the hex shape and globe. 
* Remove the mouse pointer.
* Add `<html>` over the globe icon.

Icon should be "at least 128x128 pixels (256x256 for Retina screens)." PNG preferred.
 
We could use this for the extension pack, then modify it for CIS133DA and CIS233DA by placing a roman number behind it to indicate the course level (i.e., level 1 = I, level 2 = II).

**Comment by ExploreLearnMake** [comment]
@murrayinman Could you work on packaging this extension pack and adding it to the VS Code marketplace? I would like to test it out to make sure it will work well for students.

**Comment by murrayinman** [comment]
For reference, the stock image is [#401325460](https://stock.adobe.com/images/simple-shield-with-gear-and-podcast-microphone/401325460).

The [example icon](https://github.com/rsc-media/extension-pack-webdev-student/blob/cb23901ed4dea74a5c038048c52b6bc8fc9b45cc/assets/codeGearIcon.png) was uploaded to the assets folder.

Don't use the Rio Logo.

Three icon designs with the following characters:
1. `</>`
2. `<I>`
3. `<II>`

Icon 1 should be produced in PNG 128x128 and 256x256 px and uploaded into GH icons folder.
